version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wallet-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin
    container_name: wallet-zipkin
    ports:
      - "9411:9411"
    networks:
      - wallet-network

  prometheus:
    image: prom/prometheus
    container_name: wallet-prometheus
    ports:
      - "9090:9090"
    # volumes:
    #   - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - wallet-network

networks:
  wallet-network:
    driver: bridge

volumes:
  postgres-data:
